# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\iniziaTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from Controller.ControllerTestGame import ControllerTestGame

import random

class IniziaTestView(object):

    def setupUi(self, MainWindow, currentUtilizzatore, testSelezionato):
        self.currentUtilizzatore = currentUtilizzatore
        self.testSelezionato = testSelezionato

        controllerTestGame = ControllerTestGame()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TimerLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimerLabel.setGeometry(QtCore.QRect(325, 100, 141, 90))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.TimerLabel.setFont(font)
        self.TimerLabel.setObjectName("TimerLabel")

        self.TestDisplayLabel = QtWidgets.QLabel(self.centralwidget)
        self.TestDisplayLabel.setGeometry(QtCore.QRect(90, 260, 600, 180))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TestDisplayLabel.setFont(font)
        self.TestDisplayLabel.setObjectName("TestDisplayLabel")
        self.TestDisplayLabel.setWordWrap(True)

        self.WordInputLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.WordInputLineEdit.setGeometry(QtCore.QRect(90, 500, 600, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.WordInputLineEdit.setFont(font)
        self.WordInputLineEdit.setObjectName("WordInputLineEdit")
        self.WordInputLineEdit.setFocusPolicy(Qt.StrongFocus)
        self.WordInputLineEdit.textChanged.connect(controllerTestGame.start('<KeyPress>'))

        self.PauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.PauseButton.setGeometry(QtCore.QRect(310, 560, 150, 30))
        self.PauseButton.setObjectName("PauseButton")
        self.PauseButton.clicked.connect(controllerTestGame.reset)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TimerLabel.setText(_translate("MainWindow", ''))
        self.TestDisplayLabel.setText(_translate("MainWindow", ''))
        self.PauseButton.setText(_translate("MainWindow", "Pausa/Riprendi"))
        self.WordInputLineEdit.setPlaceholderText(_translate("MainWindow", "Inizia a scrivere per avviare il test!"))

    def actionRenderizzaTest(self):
        self.TestDisplayLabel.setText(self.testSelezionato.shuffleTest())