# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogInButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogInButton.setGeometry(QtCore.QRect(150, 490, 150, 30))
        self.LogInButton.setObjectName("LogInButton")
        self.RegistrazioneButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegistrazioneButton.setGeometry(QtCore.QRect(320, 490, 150, 30))
        self.RegistrazioneButton.setObjectName("RegistrazioneButton")
        self.RecuperaPasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.RecuperaPasswordButton.setGeometry(QtCore.QRect(490, 490, 150, 30))
        self.RecuperaPasswordButton.setObjectName("RecuperaPasswordButton")
        self.UsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameInput.setGeometry(QtCore.QRect(150, 390, 491, 30))
        self.UsernameInput.setObjectName("UsernameInput")
        self.PasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordInput.setGeometry(QtCore.QRect(150, 440, 491, 30))
        self.PasswordInput.setObjectName("PasswordInput")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(80, 240, 631, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label1.setFont(font)
        self.label1.setAcceptDrops(False)
        self.label1.setObjectName("label1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LogInButton.setText(_translate("MainWindow", "LogIn"))
        self.RegistrazioneButton.setText(_translate("MainWindow", "Registrazione"))
        self.RecuperaPasswordButton.setText(_translate("MainWindow", "Recupera Password"))
        self.UsernameInput.setText(_translate("MainWindow", "Username"))
        self.PasswordInput.setText(_translate("MainWindow", "Password"))
        self.label1.setText(_translate("MainWindow", "Benvenuto in Typing Trainer!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
