# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModificaProfiloView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ModificaProfiloView(object):
    def setupUi(self, MainWindow, utenteDaModificare):
        self.utenteDaModificare = utenteDaModificare

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.modificaButton = QtWidgets.QPushButton(self.centralwidget)
        self.modificaButton.setGeometry(QtCore.QRect(320, 490, 150, 30))
        self.modificaButton.setObjectName("modificaButton")
        self.UsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameInput.setGeometry(QtCore.QRect(150, 390, 491, 30))
        self.UsernameInput.setObjectName("UsernameInput")
        self.PasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordInput.setGeometry(QtCore.QRect(150, 440, 491, 30))
        self.PasswordInput.setObjectName("PasswordInput")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(110, 200, 631, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label1.setFont(font)
        self.label1.setAcceptDrops(False)
        self.label1.setObjectName("label1")
        self.EmailInput = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailInput.setGeometry(QtCore.QRect(150, 340, 491, 30))
        self.EmailInput.setObjectName("EmailInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modificaButton.setText(_translate("MainWindow", "Modifica"))
        self.UsernameInput.setText(_translate("MainWindow", " "))
        self.UsernameInput.setPlaceholderText(_translate("MainWindow", self.utenteDaModificare.getUsername()))
        self.PasswordInput.setText(_translate("MainWindow", " "))
        self.PasswordInput.setPlaceholderText(_translate("MainWindow", self.utenteDaModificare.getPassword()))
        self.label1.setText(_translate("MainWindow", "Modifica le tue credenziali!"))
        self.EmailInput.setText(_translate("MainWindow", " "))
        self.EmailInput.setPlaceholderText(_translate("MainWindow", self.utenteDaModificare.getEmail()))
