# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecuperaPasswordView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Controller.ControllerAutenticazione import ControllerAutenticazione
from PyQt5.QtWidgets import QMessageBox


class RecuperaPasswordView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RecuperaPasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.RecuperaPasswordButton.setGeometry(QtCore.QRect(320, 490, 150, 30))
        self.RecuperaPasswordButton.setObjectName("RecuperaPasswordButton")
        self.RecuperaPasswordButton.clicked.connect(self.goRecuperaPassword)

        self.UsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameInput.setGeometry(QtCore.QRect(150, 390, 491, 30))
        self.UsernameInput.setObjectName("UsernameInput")

        self.NuovaPasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.NuovaPasswordInput.setGeometry(QtCore.QRect(150, 440, 491, 30))
        self.NuovaPasswordInput.setObjectName("NuovaPasswordInput")

        self.IdInput = QtWidgets.QLineEdit(self.centralwidget)
        self.IdInput.setGeometry(QtCore.QRect(150, 340, 491, 30))
        self.IdInput.setObjectName("IdInput")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(80, 240, 631, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label1.setFont(font)
        self.label1.setAcceptDrops(False)
        self.label1.setObjectName("label1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RecuperaPasswordButton.setText(_translate("MainWindow", "Recupera Password"))
        self.UsernameInput.setText(_translate("MainWindow", ""))
        self.UsernameInput.setPlaceholderText(_translate("MainWindow", "Username"))
        self.NuovaPasswordInput.setText(_translate("MainWindow", ""))
        self.NuovaPasswordInput.setPlaceholderText(_translate("MainWindow", "Nuova Password"))
        self.NuovaPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.NuovaPasswordInput.setText(_translate("MainWindow", ""))
        self.IdInput.setText(_translate("MainWindow", ""))
        self.IdInput.setPlaceholderText(_translate("MainWindow", "Id"))
        self.label1.setText(_translate("MainWindow", "Recupera la tua Password!"))
    
    def goRecuperaPassword(self):
        if self.UsernameInput.text() == "":
            usernameVuoto = QMessageBox()
            usernameVuoto.setWindowTitle("Errore!")
            usernameVuoto.setText("Nessun username inserito!")
            usernameVuoto.exec_()
            return
        if self.NuovaPasswordInput.text() == "":
            nuovaPasswordVuoto = QMessageBox()
            nuovaPasswordVuoto.setWindowTitle("Errore!")
            nuovaPasswordVuoto.setText("Nessuna password inserita!")
            nuovaPasswordVuoto.exec_()
            return
        if self.IdInput.text() == "":
            IdVuoto = QMessageBox()
            IdVuoto.setWindowTitle("Errore!")
            IdVuoto.setText("Nessun Id inserito!")
            IdVuoto.exec_()
            return

        self.controllerAutenticazione = ControllerAutenticazione()
        recovered = self.controllerAutenticazione.recuperaPassword(int(self.IdInput.text()), self.UsernameInput.text(), self.NuovaPasswordInput.text())
        if recovered==True:
            recuperoOK = QMessageBox()
            recuperoOK.setWindowTitle("OK")
            recuperoOK.setText("Recupero effettuato con successo!")
            recuperoOK.exec_()
        else:
            recuperoNonOK = QMessageBox()
            recuperoNonOK.setWindowTitle("Errore!")
            recuperoNonOK.setText("Recupero non effettuato!")
            recuperoNonOK.exec_()
