# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecuperaPasswordView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Controller.ControllerAutenticazione import ControllerAutenticazione
from PyQt5.QtWidgets import QMessageBox


class RecuperaPasswordView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RecuperaPasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.RecuperaPasswordButton.setGeometry(QtCore.QRect(320, 490, 150, 30))
        self.RecuperaPasswordButton.setObjectName("RecuperaPasswordButton")
        self.RecuperaPasswordButton.clicked.connect(self.actionRecuperaPassword)

        self.IdentifierInput = QtWidgets.QLineEdit(self.centralwidget)
        self.IdentifierInput.setGeometry(QtCore.QRect(150, 390, 491, 30))
        self.IdentifierInput.setObjectName("IdentifierInput")

        self.NuovaPasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.NuovaPasswordInput.setGeometry(QtCore.QRect(150, 440, 491, 30))
        self.NuovaPasswordInput.setObjectName("NuovaPasswordInput")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(80, 240, 631, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label1.setFont(font)
        self.label1.setAcceptDrops(False)
        self.label1.setObjectName("label1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RecuperaPasswordButton.setText(_translate("MainWindow", "Recupera Password"))
        self.NuovaPasswordInput.setText(_translate("MainWindow", ""))
        self.NuovaPasswordInput.setPlaceholderText(_translate("MainWindow", "Nuova Password"))
        self.NuovaPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.NuovaPasswordInput.setText(_translate("MainWindow", ""))
        self.IdentifierInput.setText(_translate("MainWindow", ""))
        self.IdentifierInput.setPlaceholderText(_translate("MainWindow", "Identificatore"))
        self.label1.setText(_translate("MainWindow", "Recupera la tua Password!"))
    
    def actionRecuperaPassword(self):
        self.controllaCampoIdentifierNonVuoto()
        self.controllaCampoNuovaPasswordNonVuoto()

        self.controllerAutenticazione = ControllerAutenticazione()
        self.recovered = self.controllerAutenticazione.recuperaPassword(int(self.IdentifierInput.text()), self.NuovaPasswordInput.text())
        
        self.controllaRecuperoPasswordEffettuatoConSuccesso()

    def controllaCampoNuovaPasswordNonVuoto(self):
        if self.NuovaPasswordInput.text() == "":
            nuovaPasswordVuoto = QMessageBox()
            nuovaPasswordVuoto.setWindowTitle("Errore!")
            nuovaPasswordVuoto.setText("Nessuna password inserita!")
            nuovaPasswordVuoto.exec_()
            return

    def controllaCampoIdentifierNonVuoto(self):
        if self.IdentifierInput.text() == "":
            IdentifierVuoto = QMessageBox()
            IdentifierVuoto.setWindowTitle("Errore!")
            IdentifierVuoto.setText("Nessun Id inserito!")
            IdentifierVuoto.exec_()
            return

    def controllaRecuperoPasswordEffettuatoConSuccesso(self):
        if self.recovered==True:
            recuperoOK = QMessageBox()
            recuperoOK.setWindowTitle("OK")
            recuperoOK.setText("Recupero effettuato con successo!")
            recuperoOK.exec_()
        else:
            recuperoNonOK = QMessageBox()
            recuperoNonOK.setWindowTitle("Errore!")
            recuperoNonOK.setText("Recupero non effettuato!")
            recuperoNonOK.exec_()