# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualizzaProfiloView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Controller import ControllerAutenticazione, ControllerUtente
from View.ModificaProfiloView import ModificaProfiloView

class VisualizzaProfiloView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(140, 190, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.modificaProfiloButton = QtWidgets.QPushButton(self.centralwidget)
        self.modificaProfiloButton.setGeometry(QtCore.QRect(440, 210, 150, 30))
        self.modificaProfiloButton.setObjectName("modificaProfiloButton")
        self.modificaProfiloButton.clicked.connect(self.goModificaProfilo)

        self.logOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logOutButton.setGeometry(QtCore.QRect(440, 260, 150, 30))
        self.logOutButton.setObjectName("logOutButton")
        self.logOutButton.clicked.connect(self.goLogOut)

        self.joinedInLabel = QtWidgets.QLabel(self.centralwidget)
        self.joinedInLabel.setGeometry(QtCore.QRect(150, 270, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.joinedInLabel.setFont(font)
        self.joinedInLabel.setObjectName("joinedInLabel")
        self.dateLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel.setGeometry(QtCore.QRect(230, 270, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateLabel.setFont(font)
        self.dateLabel.setObjectName("dateLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 320, 350, 62))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 320, 350, 62))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 510, 350, 62))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 510, 350, 62))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernameLabel.setText(_translate("MainWindow", self.utente.getUsername()))
        self.modificaProfiloButton.setText(_translate("MainWindow", "Modifica Profilo"))
        self.logOutButton.setText(_translate("MainWindow", "Log Out"))
        self.joinedInLabel.setText(_translate("MainWindow", "Joined in,"))
        self.dateLabel.setText(_translate("MainWindow", self.utente.getDataOraCreazione()))
        self.label.setText(_translate("MainWindow", "Totale Test Eseguiti"))
        self.label_2.setText(_translate("MainWindow", "Precisione Media (%)"))
        self.label_3.setText(_translate("MainWindow", "Media WPM"))
        self.label_4.setText(_translate("MainWindow", "Media errori per test"))

    def goModificaProfilo(self):
        self.modificaProfilo = QtWidgets.QMainWindow()
        self.ui = ModificaProfiloView()
        self.ui.setupUi(self.modificaProfilo)
        self.modificaProfilo.show()
    
    def goLogOut(self):
        self.controllerAutenticazione = ControllerAutenticazione()
        self.controllerAutenticazione.logOut()
